version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:80"

    volumes:
      - .:/var/www/html
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf